"""Add image1_path and other image fields to Post

Revision ID: db6b431f6e94
Revises: 11d55097f9c0
Create Date: 2024-12-15 23:43:59.151223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6b431f6e94'
down_revision = '11d55097f9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image2_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image3_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image4_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image4_path')
        batch_op.drop_column('image3_path')
        batch_op.drop_column('image2_path')
        batch_op.drop_column('image1_path')

    # ### end Alembic commands ###
